import raw from "./generated/serviceCalendar.json";

// Service calendar derived from MTA GTFS *static* feeds, regenerated by
// `npm run build:calendar` (see scripts/build-service-calendar.mjs). The
// realtime alert feed carries no future-dated entries, so a forward-looking
// calendar has to come from the scheduled data.
//
// The month grid and "today" are computed here rather than baked into the
// artifact — the old mock froze `today: 16` and a month string, so the
// calendar was wrong the next day.

export type DayType = "weekday" | "saturday" | "sunday";

export interface ServiceException {
  date: string; // YYYY-MM-DD
  naturalType: DayType;
  effectiveType: DayType;
  label: string;
  feeds: string[];
}

export interface ServiceCalendarSource {
  generatedAt: string;
  source: string;
  rangeStart: string | null; // YYYYMMDD
  rangeEnd: string | null;
  feeds: { id: string; label: string; version: string | null }[];
  exceptions: ServiceException[];
}

export const serviceCalendar = raw as ServiceCalendarSource;

function isoDate(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

/** "20260905" -> Date (local noon, so DST never shifts the calendar day). */
export function parseCompact(compact: string | null): Date | null {
  if (!compact || compact.length !== 8) return null;
  return new Date(
    Number(compact.slice(0, 4)),
    Number(compact.slice(4, 6)) - 1,
    Number(compact.slice(6, 8)),
    12
  );
}

export interface CalendarCell {
  day: number | null;
  date: string | null;
  isToday: boolean;
  exception: ServiceException | null;
  inFeedRange: boolean;
}

/**
 * A Sunday-first month grid. Cells outside the feed's coverage window are
 * marked so the UI can distinguish "no schedule change" from "we have no
 * scheduled data for this date".
 */
export function buildMonthGrid(
  year: number,
  month: number, // 0-indexed
  exceptions: ServiceException[],
  today = new Date()
): CalendarCell[][] {
  const byDate = new Map(exceptions.map((e) => [e.date, e]));
  const rangeStart = parseCompact(serviceCalendar.rangeStart);
  const rangeEnd = parseCompact(serviceCalendar.rangeEnd);
  const todayIso = isoDate(today);

  const first = new Date(year, month, 1, 12);
  const daysInMonth = new Date(year, month + 1, 0).getDate();
  const lead = first.getDay();

  const cells: CalendarCell[] = [];
  for (let i = 0; i < lead; i++) {
    cells.push({ day: null, date: null, isToday: false, exception: null, inFeedRange: false });
  }
  for (let day = 1; day <= daysInMonth; day++) {
    const d = new Date(year, month, day, 12);
    const iso = isoDate(d);
    cells.push({
      day,
      date: iso,
      isToday: iso === todayIso,
      exception: byDate.get(iso) ?? null,
      inFeedRange: !!rangeStart && !!rangeEnd && d >= rangeStart && d <= rangeEnd,
    });
  }
  while (cells.length % 7 !== 0) {
    cells.push({ day: null, date: null, isToday: false, exception: null, inFeedRange: false });
  }

  const weeks: CalendarCell[][] = [];
  for (let i = 0; i < cells.length; i += 7) weeks.push(cells.slice(i, i + 7));
  return weeks;
}

/** Schedule changes from today onwards, soonest first. */
export function upcomingExceptions(
  exceptions: ServiceException[],
  today = new Date(),
  limit = 6
): ServiceException[] {
  const todayIso = isoDate(today);
  return exceptions
    .filter((e) => e.date >= todayIso)
    .sort((a, b) => a.date.localeCompare(b.date))
    .slice(0, limit);
}

export function formatExceptionDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(y, m - 1, d, 12).toLocaleDateString(undefined, {
    weekday: "short",
    month: "short",
    day: "numeric",
  });
}
